
DOCS = switch-slides
DIAGRAMS = \
	   diagrams/address-aging.pdf \
	   diagrams/collision.pdf \
	   diagrams/ethernet-frame.pdf \
	   diagrams/frame-transmission.pdf \
	   diagrams/global-network.pdf \
	   diagrams/learning.pdf \
	   diagrams/managed-switch.pdf \
	   diagrams/repeater.pdf \
	   diagrams/switch-buffer.pdf \
	   diagrams/switch.pdf \
	   diagrams/virtual-network.pdf

include ../Makefile.common
