
DOCS = server-sockets-slides
DIAGRAMS = \
	   diagrams/before-binding.pdf \
	   diagrams/http-external.pdf \
	   diagrams/http-files.pdf \
	   diagrams/http-inernal.pdf \
	   diagrams/ingress-queue.pdf \
	   diagrams/listening-socket.pdf \
	   diagrams/multiple-clients.pdf \
	   diagrams/stream-server-algorithm.pdf \
	   diagrams/transmitting-socket-creation.pdf \
	   diagrams/transmitting-socket.pdf \
	   diagrams/web.pdf

include ../Makefile.common
