
CONTEXT = context

SUBDOCS = $(SRCDIR)/netprog-course $(SRCDIR)/netprog-env $(SRCDIR)/slides-env $(SRCDIR)/practice-env
PDF = $(DOCS:=.pdf)
SRC = $(DOCS:=.tex) $(SUBDOCS:=.tex)

all : $(PDF)

$(PDF) : $(SRC) $(DIAGRAMS)
$(PDF) : %.pdf : %.tex
	$(CONTEXT) $<

clean :
	rm -f $(PDF) *.tuc *.aux *.bbl *.blg *.log

.PHONY : all clean
