
DOCS = file-descriptors-slides class-task
DIAGRAMS = \
	   diagrams/data-redirection.pdf \
	   diagrams/disks-volumes.pdf \
	   diagrams/file-hierarchy.pdf \
	   diagrams/inode-dentry.pdf \
	   diagrams/io-buffering.pdf \
	   diagrams/io-streams.pdf \
	   diagrams/mounting-points.pdf \
	   diagrams/open-files.pdf \
	   diagrams/pipe.pdf \
	   diagrams/td-bu.pdf

include ../Makefile.common
