
CONTEXT = context

SUBDOCS = \
	  $(SRCDIR)/lectures/netprog-course \
	  $(SRCDIR)/lectures/netprog-env \
	  $(SRCDIR)/lectures/slides-env \
	  $(SRCDIR)/lectures/practice-env

PDF = $(DOCS:=.pdf)
SRC = $(DOCS:=.tex) $(SUBDOCS:=.tex)

all : $(PDF)

$(PDF) : $(SRC) $(DIAGRAMS)
$(PDF) : %.pdf : %.tex
	$(CONTEXT) $<

clean :
	rm -f $(PDF) *.tuc *.aux *.bbl *.blg *.log

.PHONY : all clean
