
DOCS = intro-slides
DIAGRAMS = \
	   diagrams/ai-yolo.png \
	   diagrams/debian-languages.png \
	   diagrams/edge-computing.png \
	   diagrams/editor.pdf \
	   diagrams/embedded-system-example.jpg \
	   diagrams/extended-environment.pdf \
	   diagrams/industrial-devices2.jpg \
	   diagrams/iot-architecture.pdf \
	   diagrams/linux-packages.png \
	   diagrams/minimal-environment.pdf \
	   diagrams/openembedded.pdf \
	   diagrams/smart-city-structure.pdf \
	   diagrams/telecom-devices.jpg \
	   diagrams/torvalds.jpg \
	   diagrams/typical-soc.pdf \
	   diagrams/unix-timeline.png \
	   diagrams/virtualbox.graphml \
	   diagrams/virtualbox.pdf

include ../Makefile.common
