
DOCS = intro-slides
DIAGRAMS = \
	   diagrams/build-stages.pdf \
	   diagrams/concept.pdf \
	   diagrams/corundum.pdf \
	   diagrams/hardware-architecture.pdf \
	   diagrams/memory-allocation.pdf \
	   diagrams/network-interaction.pdf \
	   diagrams/software-architecture.pdf

include ../Makefile.common
