
DOCS = concurrency-slides
DIAGRAMS = \
	   diagrams/concurrent-solution.pdf \
	   diagrams/parallel-solution.pdf \
	   diagrams/request.pdf \
	   diagrams/timeout-calculation.pdf \
	   diagrams/timeout-handling.pdf \
	   diagrams/web-server.pdf

include ../Makefile.common
