
DOCS = kernel-drivers-slides
DIAGRAMS = \
	   diagrams/address-space.pdf \
	   diagrams/hardware-buses.pdf \
	   diagrams/interrupts.pdf \
	   diagrams/irq-mux.pdf \
	   diagrams/timer.pdf \
	   diagrams/virtual-addresses.pdf

include ../Makefile.common
