
DOCS = unix-processes-slides
DIAGRAMS = \
	   diagrams/cow.pdf \
	   diagrams/daemons.pdf \
	   diagrams/delayed-actions.pdf \
	   diagrams/environment-modification.pdf \
	   diagrams/execution.pdf \
	   diagrams/inheritance.pdf \
	   diagrams/init.pdf \
	   diagrams/process-environment.pdf \
	   diagrams/process-forking.pdf \
	   diagrams/process-states.pdf \
	   diagrams/scheduler.pdf \
	   diagrams/signal-delivery.pdf \
	   diagrams/signal-lifecycle.pdf \
	   diagrams/waitpid.pdf

include ../Makefile.common
