
DOCS = data-formats-slides
DIAGRAMS = \
	    diagrams/json-t-tree.pdf \
	    diagrams/managed-objects.pdf \
	    diagrams/management-system.pdf \
	    diagrams/network-controller.pdf \
	    diagrams/shared-tree-decref.pdf \
	    diagrams/shared-tree-incref.pdf \
	    diagrams/shared-tree.pdf \
	    diagrams/unpack.pdf

include ../Makefile.common
