
DOCS = concurrency-slides
DIAGRAMS = \
	   diagrams/light-bulb.pdf \
	   diagrams/parallelism-redundancy.pdf \
	   diagrams/repeater.pdf \
	   diagrams/state-diagram.pdf \
	   diagrams/tcp-state-machine.pdf \
	   diagrams/timeout-calculation.pdf

include ../Makefile.common
