
DOCS = switch-slides
DIAGRAMS = \
	   diagrams/ethernet-switch.jpg \
	   diagrams/rj-45.jpg \
	   diagrams/ethernet-frame.pdf \
	   diagrams/frame-handling-algorithm.pdf \
	   diagrams/frame-transmission.pdf \
	   diagrams/low-level-traffic.pdf \
	   diagrams/repeater.pdf \
	   diagrams/repeater-transmission.pdf \
	   diagrams/software-bridge.pdf \
	   diagrams/switch-aging.pdf \
	   diagrams/switch.pdf \
	   diagrams/switch-queues.pdf \
	   diagrams/switch-topology-change.pdf \
	   diagrams/switch-transmission.pdf \
	   diagrams/topology-change.pdf \
	   diagrams/virtual-interfaces.pdf \
	   diagrams/virtual-topology.pdf

include ../Makefile.common
