
DOCS = client-sockets-slides class-task
DIAGRAMS = \
	   diagrams/network.pdf \
	   diagrams/4-layer-model-implementation.pdf \
	   diagrams/4-layer-model.pdf \
	   diagrams/ethernet-header.pdf \
	   diagrams/ftp-architecture.pdf \
	   diagrams/ftp-usage.pdf \
	   diagrams/segment-boundaries.pdf \
	   diagrams/sequence-numbering.pdf \
	   diagrams/tcp-connection.pdf \
	   diagrams/unix-sockets-in-linux.pdf \
	   diagrams/encapsulation.png \
	   diagrams/ip-header.png

include ../Makefile.common
