
DOCS = program-structure-slides
DIAGRAMS = \
	   diagrams/avl-tree.pdf \
	   diagrams/binary-tree-dictionary.pdf \
	   diagrams/dynamic-resources.pdf \
	   diagrams/event-queue.pdf \
	   diagrams/generic-list.pdf \
	   diagrams/layering.pdf \
	   diagrams/multiple-implementations.pdf \
	   diagrams/resource-indexing.pdf \
	   diagrams/sensors.pdf \
	   diagrams/sensors-task.pdf \
	   diagrams/simple-dictionary.pdf \
	   diagrams/tree-balancing.pdf

include ../Makefile.common
