
DOCS = containers-slides
DIAGRAMS = \
	   diagrams/addition-deletion.pdf \
	   diagrams/app-structure.pdf \
	   diagrams/avl-tree.pdf \
	   diagrams/container-of.pdf \
	   diagrams/generic-list.pdf \
	   diagrams/key-search.pdf \
	   diagrams/search-tree.pdf \
	   diagrams/simple-list.pdf

include ../Makefile.common
